### ISSUE TITLE
你好，我这里是格式问题吗？

### ISSUE THREAD

**Issue by moodn** [superdog125/BookWebsite_Scrapy#1]

**Comment by moodn** [comment]
{
                "绘画": "http://book.ly.superlib.net/book.do?go=guidesearch&flid=1003"  
            }, {“西方学院派油画教程 西方油画大师作品中的经典技法”:“ http://book.ly.superlib.net/views/specific/2929/bookDetail.jsp?dxNumber=000017987095&d=91E1886639CA72D0D9001FE014AD2E3F” },
            {
                "书法、篆刻": "http://book.ly.superlib.net/book.do?go=guidesearch&flid=1004"
            },
            {
                "雕塑": "http://book.ly.superlib.net/book.do?go=guidesearch&flid=1005"

**Comment by moodn** [comment]
> ![Uploading image.png…](C:\Users\Administrator\Pictures\Saved Pictures\1.png)

==== RESTART: C:\Users\Administrator\BookWebsite_Scrapy\Book_Scrapy\main.py ====
Traceback (most recent call last):
  File "C:\Users\Administrator\BookWebsite_Scrapy\Book_Scrapy\main.py", line 331, in <module>
    book = Book_Scrapy()
  File "C:\Users\Administrator\BookWebsite_Scrapy\Book_Scrapy\main.py", line 25, in __init__
    self.browser = webdriver.Chrom

**Comment by zhouzhouzhou314** [comment]
请问怎么下载里面的图书呢
